# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. 

Use the links below to read the data files using the Pandas library. 

* Chicago Census Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Public Schools

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Crime Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

**NOTE:** Ensure you use the datasets available on the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Load the `pandas` and `sqlite3` libraries and establish a connection to `FinalDB.db`

In [1]:
import pandas as pd
import sqlite3
con = sqlite3.connect('FinalDB.db')

Load the SQL magic module

In [2]:
%load_ext sql

Use `Pandas` to load the data available in the links above to dataframes. Use these dataframes to load data on to the database `FinalDB.db` as required tables.

In [3]:
df1 = pd.read_csv('ChicagoCensusData.csv')
df2 = pd.read_csv('ChicagoPublicSchools.csv')
df3 = pd.read_csv('ChicagoCrimeData.csv')

df1.to_sql('Chicago_Census_Data', con, if_exists='replace', index=False)
df2.to_sql('Chicago_Public_Schools', con, if_exists='replace', index=False)
df3.to_sql('Chicago_Crime_Data', con, if_exists='replace', index=False)

533

Establish a connection between SQL magic module and the database `FinalDB.db`

In [4]:
%sql sqlite:///FinalDB.db

Connecting to 'sqlite:///FinalDB.db'

You can now proceed to the the following questions. Please note that a graded assignment will follow this lab and there will be a question on each of the problems stated below. It can be from the answer you received or the code you write for this problem. Therefore, please keep a note of both your codes as well as the response you generate.

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [9]:
%%sql
select count(*) as 'total number of crimes recorded'
from Chicago_Crime_Data

Running query in 'sqlite:///FinalDB.db'

+---------------------------------+
| total number of crimes recorded |
+---------------------------------+
|               533               |
+---------------------------------+

### Problem 2

##### List community area names and numbers with per capita income less than 11000.

In [13]:
%%sql
select COMMUNITY_AREA_NAME, COMMUNITY_AREA_NUMBER
from Chicago_Census_Data
where PER_CAPITA_INCOME < 11000

Running query in 'sqlite:///FinalDB.db'

+---------------------+-----------------------+
| COMMUNITY_AREA_NAME | COMMUNITY_AREA_NUMBER |
+---------------------+-----------------------+
|  West Garfield Park |          26.0         |
|    South Lawndale   |          30.0         |
|     Fuller Park     |          37.0         |
|      Riverdale      |          54.0         |
+---------------------+-----------------------+

### Problem 3

##### List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [17]:
%%sql
select CASE_NUMBER
from Chicago_Crime_Data
where lower(DESCRIPTION) like '%minor%'

Running query in 'sqlite:///FinalDB.db'

+-------------+
| CASE_NUMBER |
+-------------+
|   HL266884  |
|   HK238408  |
+-------------+

### Problem 4

##### List all kidnapping crimes involving a child?

In [20]:
%%sql
select *
from Chicago_Crime_Data
where lower(PRIMARY_TYPE) li    ke '%kidnapping' and lower(DESCRIPTION) like '%child%'

Running query in 'sqlite:///FinalDB.db'

+---------+-------------+------------+----------------------+------+--------------+--------------------------+----------------------+--------+----------+------+----------+------+-----------------------+---------+--------------+--------------+------+-------------+--------------+-------------------------------+
|    ID   | CASE_NUMBER |    DATE    |        BLOCK         | IUCR | PRIMARY_TYPE |       DESCRIPTION        | LOCATION_DESCRIPTION | ARREST | DOMESTIC | BEAT | DISTRICT | WARD | COMMUNITY_AREA_NUMBER | FBICODE | X_COORDINATE | Y_COORDINATE | YEAR |   LATITUDE  |  LONGITUDE   |            LOCATION           |
+---------+-------------+------------+----------------------+------+--------------+--------------------------+----------------------+--------+----------+------+----------+------+-----------------------+---------+--------------+--------------+------+-------------+--------------+-------------------------------+
| 5276766 |   HN144152  | 2007-01-26 | 050XX W VAN BUREN ST | 1792 |  KIDNAPPING  | CHILD ABDUCTION/STRANGER |        STREET        |   0    |    0     | 1533 |    15    | 29.0 |          25.0         |    20   |  1143050.0   |  1897546.0   | 2007 | 41.87490841 | -87.75024931 | (41.874908413, -87.750249307) |
+---------+-------------+------------+----------------------+------+--------------+--------------------------+----------------------+--------+----------+------+----------+------+-----------------------+---------+--------------+--------------+------+-------------+--------------+-------------------------------+

### Problem 5

##### List the kind of crimes that were recorded at schools. (No repetitions)

In [22]:
%%sql
select distinct PRIMARY_TYPE
from Chicago_Crime_Data
where lower(LOCATION_DESCRIPTION) like '%school%'

Running query in 'sqlite:///FinalDB.db'

+------------------------+
|      PRIMARY_TYPE      |
+------------------------+
|        BATTERY         |
|    CRIMINAL DAMAGE     |
|       NARCOTICS        |
|        ASSAULT         |
|   CRIMINAL TRESPASS    |
| PUBLIC PEACE VIOLATION |
+------------------------+

### Problem 6

##### List the type of schools along with the average safety score for each type.

In [24]:
%%sql
select "Elementary, Middle, or High School", avg(safety_score)
from Chicago_Public_Schools
group by  "Elementary, Middle, or High School"

Running query in 'sqlite:///FinalDB.db'

+------------------------------------+-------------------+
| Elementary, Middle, or High School | avg(safety_score) |
+------------------------------------+-------------------+
|                 ES                 | 49.52038369304557 |
|                 HS                 | 49.62352941176471 |
|                 MS                 |        48.0       |
+------------------------------------+-------------------+

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [26]:
%%sql
select COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY
from Chicago_Census_Data
order by PERCENT_HOUSEHOLDS_BELOW_POVERTY desc
limit 5

Running query in 'sqlite:///FinalDB.db'

+---------------------+----------------------------------+
| COMMUNITY_AREA_NAME | PERCENT_HOUSEHOLDS_BELOW_POVERTY |
+---------------------+----------------------------------+
|      Riverdale      |               56.5               |
|     Fuller Park     |               51.2               |
|      Englewood      |               46.6               |
|    North Lawndale   |               43.1               |
|  East Garfield Park |               42.4               |
+---------------------+----------------------------------+

### Problem 8

##### Which community area is most crime prone? Display the coumminty area number only.

In [30]:
%%sql 
select COMMUNITY_AREA_NUMBER
from Chicago_Crime_Data
group by COMMUNITY_AREA_NUMBER
order by count(*) desc
limit 1

Running query in 'sqlite:///FinalDB.db'

+-----------------------+
| COMMUNITY_AREA_NUMBER |
+-----------------------+
|          25.0         |
+-----------------------+


Double-click **here** for a hint

<!--
Query for the 'community area number' that has most number of incidents
-->

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [31]:
%%sql
select COMMUNITY_AREA_NAME
from Chicago_Census_Data
where HARDSHIP_INDEX = (select max(HARDSHIP_INDEX) from Chicago_Census_Data)

Running query in 'sqlite:///FinalDB.db'

+---------------------+
| COMMUNITY_AREA_NAME |
+---------------------+
|      Riverdale      |
+---------------------+

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [34]:
%%sql
select COMMUNITY_AREA_NAME, COMMUNITY_AREA_NUMBER
from Chicago_Census_Data
where COMMUNITY_AREA_NUMBER = 
( select COMMUNITY_AREA_NUMBER 
from Chicago_Crime_Data 
group by COMMUNITY_AREA_NUMBER
order by count(*) desc
limit 1
)

Running query in 'sqlite:///FinalDB.db'

+---------------------+-----------------------+
| COMMUNITY_AREA_NAME | COMMUNITY_AREA_NUMBER |
+---------------------+-----------------------+
|        Austin       |          25.0         |
+---------------------+-----------------------+